package com.embabel.agent.rag.model

import io.swagger.v3.oas.annotations.media.Schema

/**
 * Root of all data objects.
 * Data object instance, whether structural (from a literal source)
 * or not.
 */
sealed interface Datum {

    /**
     * Embabel id. Will be synthetic.
     */
    val id: String

    /**
     * URI for the content. May be a URL.
     * Not generated by Embabel, but from the source.
     */
    val uri: String?

    val metadata: Map<String, Any?>

    /**
     * Properties to persist
     * Subclasses can add their own properties
     * but must call super to include these.
     */
    fun propertiesToPersist(): Map<String, Any?> = mapOf(
        "id" to id,
        "uri" to uri,
    ) + metadata

    /**
     * Labels of the entity. In Neo, this might include multiple labels.
     * In a relational database, this might be a single table name.
     */
    @Schema(
        description = "Labels of the content element. In Neo, this might include multiple labels. In a relational database, this might be a single table name.",
        example = "[\"Person\", \"Customer\"]",
        required = true,
    )
    fun labels(): Set<String> = emptySet()
}